In [1]:
import numpy as np
import sys

**The Basics**

In [2]:
a = np.array([1,2,3],dtype='int64')
print(a)

[1 2 3]


In [3]:
a.dtype

dtype('int64')

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#get dimension(1d, 2d, 3d  ....etc.)
a.ndim


1

In [6]:
b.ndim

2

In [7]:
#get shape
b.shape

(2, 3)

In [8]:
b.itemsize

8

In [9]:
# Get total size
a.nbytes #[1,2,3]-----> 3*8= 24

24

In [10]:
b.size#total elements

6

**Accessing/Changing specific elements, rows, columns, etc
**

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [13]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 5]

array([ 6, 13])

In [15]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[1,1::1 ]

array([ 9, 10, 11, 12, 13, 14])

In [16]:
a[1,5]=50 # value replacement
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 50 14]]


In [17]:
a[:,2]=5# that changed the both row and 3 no coloumns value

print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 50 14]]


In [18]:
#3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
three_d_array= np.array([[[10,20], [30,40], [50,60], [70,80]]])
print(three_d_array)

[[[10 20]
  [30 40]
  [50 60]
  [70 80]]]


In [20]:
three_d_array[:,3]

array([[70, 80]])

In [21]:
#replace
three_d_array[:,1]= 2, 20
print(three_d_array)

[[[10 20]
  [ 2 20]
  [50 60]
  [70 80]]]



**Initializing Different Types of Arrays**

In [22]:
# All 0s matrix
np.zeros((3,3), dtype='int64')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
#All 1s matrix
np.ones((4,2,2), dtype='int64')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
np.full((2,2), 69, dtype='int64')

array([[69, 69],
       [69, 69]])

In [25]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
#random decimal numbers
np.random.rand(4,3)

array([[0.35129481, 0.80499829, 0.37051213],
       [0.18843438, 0.86565977, 0.89589839],
       [0.38892931, 0.41628585, 0.35846467],
       [0.85299354, 0.14345667, 0.72277605]])

In [27]:
# Random Integer values
np.random.randint(120,290, size=(4,4))

array([[226, 199, 177, 234],
       [194, 121, 187, 179],
       [257, 129, 169, 127],
       [201, 166, 268, 233]], dtype=int32)

In [28]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# Repeat an array

arr = np.array([[1,2,3]])  # This is a 2D array with one row and three columns
r1 = np.repeat(arr,3, axis=0)  # This is a 2D array with one row and three columns
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
z = np.zeros((3,3,3))# 3d matrix

z[1,1,1] = 9#

print(z)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 9. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [31]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)


output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
a = np.array([1,2,3])
b = a.copy()


b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


**Mathematics**

In [33]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a + 2

array([3, 4, 5, 6])

In [35]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [36]:
a ** 2

array([ 1,  4,  9, 16])

In [37]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [38]:
# for all mathmathics Function
# visit: https://numpy.org/doc/stable/reference/routines.math.html

**Linear Algebra**

In [39]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) #  Matrix Multiplication

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

**Statistics**

In [41]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats)

np.int64(1)

In [43]:
np.max(stats, axis=1)
#axis=1 means that we want to find the maximum value along the rows (horizontally).

array([3, 6])

In [44]:
np.sum(stats, axis=0)
# sum will be calculated along each column (vertically)

array([5, 7, 9])

In [45]:
np.sum(stats, axis=1)
# sum will be calculated along each column (horizontally)

array([ 6, 15])